### ISSUE TITLE
Add tabs into team page layout

### ISSUE THREAD

**Issue by WesleyTheGeolien** [CEREGE-CL/CEREGE-CL.github.io#4]
It woujld be good to have extra tabs in people personal pages to be able to add CVs and other information to the website.

@AntaCl

**Comment by AntaC-Sarr** [comment]
Thought about that : I think maybe it does not worth it ... only having a short introductory text with a link to personal website could be an alternative as many already have personal page on lab websites for example (+in that case, when you leave the group you still have your personal website that you can update with whatever your are doing !)

**Comment by WesleyTheGeolien** [comment]
ok Ill close this then
